Import('env', 'arch', 'messaging', 'common', 'visionipc', 'device')
import os

# OpenCL after visionipc: libvisionipc.a (visionbuf_cl.cc) references CL symbols.
libs = [common, messaging, visionipc, 'jpeg', 'yuv']
if device == 'KA2':
  libs += ['rga']
libs += ['OpenCL']

if arch != "Darwin":
  camerad_env = env.Clone()
  # KA2: only RK camera and ox03c10. No os04c10, no TICI-specific ar0231.
  if device == 'KA2':
    camerad_env.Append(CPPDEFINES=['OP_DEVICE_KA2'])
    camerad_src = ['cameras/camera_rk.cc', 'cameras/camera_common.cc',
                   'sensors/ox03c10.cc']
  else:
    camerad_src = ['cameras/camera_rk.cc', 'cameras/camera_common.cc',
                   'sensors/ox03c10.cc', 'sensors/os04c10.cc']
    if os.path.exists(env.Dir('#system/camerad').File('sensors/ar0231.cc').abspath):
      camerad_src.append('sensors/ar0231.cc')
  camera_obj = camerad_env.Object(camerad_src)
  env.Program('camerad', ['main.cc', camera_obj], LIBS=libs)

  if GetOption("extras") and arch == "x86_64":
    env.Program('test/test_ae_gray', ['test/test_ae_gray.cc', camera_obj], LIBS=libs)
