Import('device', 'build_gui')

SConscript(['pandad/SConscript'])
SConscript(['controls/lib/lateral_mpc_lib/SConscript'])
SConscript(['controls/lib/longitudinal_mpc_lib/SConscript'])
SConscript(['locationd/SConscript'])
SConscript(['modeld/SConscript'])

# No UI on KA2 (headless / no raylib or installer build).
if build_gui:
  SConscript(['ui/SConscript'])
